apiVersion: apps/v1
kind: Deployment
metadata:
  name: predictservice
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: predictservice
  template:
    metadata:
      name: predictservice
      labels:
        app: predictservice
    spec:
      containers:
        - name: predictservice
          image: miptuser/predictservice
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: predict
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: predictservice
  type: ClusterIP
